#!/bin/sh

PREREQ=""

prereqs()
{
        echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /sbin/mdadm /sbin
copy_exec /sbin/partprobe /sbin
copy_exec /sbin/parted /sbin
copy_exec /sbin/mkfs.ext4 /sbin
copy_exec /sbin/e2label /sbin
